steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml']

  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args: ['install']
    dir: 'customer'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml']
    dir: 'customer'

  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args: ['install']
    dir: 'admin'

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml']
    dir: 'admin'